/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: string;
  typology?:
    | "residential"
    | "commercial"
    | "industrial"
    | "mixed-use"
    | "interior"
    | "other";
  status?: "Completed" | "In progress" | "Concept";
  duration?: string;
  completionDate?: string;
  biography?: RichText;
  heroImage?: ContentImage;
  overviewDescription?: RichText;
  overviewImage?: ContentImage;
  gallery?: Array<
    {
      _key: string;
    } & ContentImage
  >;
  details?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  detailsImage?: ContentImage;
  featured?: boolean;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentImage = {
  _type: "contentImage";
  asset?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  caption?: string;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type WorkPage = {
  _id: string;
  _type: "workPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  hero?: HeroMedia;
  exploreMoreIntroduction?: RichText;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type HeroMedia = {
  _type: "heroMedia";
  mediaType?: "image" | "video";
  image?: ContentImage;
  video?: ContentVideo;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  membershipStatus?: "current" | "former";
  role?: string;
  portrait?: ContentImage;
  biography?: RichText;
  startYear?: number;
  endYear?: number;
  visibility?: "visible" | "hidden";
  order?: number;
};

export type TeamPage = {
  _id: string;
  _type: "teamPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: RichText;
  hero?: HeroMedia;
  currentTeamTitle?: string;
  formerTeamTitle?: string;
  formerTeamIntroduction?: RichText;
  callToAction?: CallToAction;
};

export type CallToAction = {
  _type: "callToAction";
  title?: string;
  description?: RichText;
  label?: string;
  href?: string;
  backgroundImage?: ContentImage;
  insetImage?: ContentImage;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  summary?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: HeroMedia;
  aboutTitle?: string;
  introduction?: RichText;
  resources?: Array<{
    title?: string;
    body?: RichText;
    _key: string;
  }>;
  beliefs?: Array<{
    title?: string;
    body?: RichText;
    _key: string;
  }>;
  principles?: Array<{
    lead?: string;
    body?: RichText;
    largeImage?: ContentImage;
    smallImage?: ContentImage;
    _key: string;
  }>;
  callToAction?: CallToAction;
};

export type ContentVideo = {
  _type: "contentVideo";
  url?: string;
  poster?: ContentImage;
  title?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Project
  | SanityImageAssetReference
  | ContentImage
  | RichText
  | Slug
  | ProjectReference
  | WorkPage
  | HeroMedia
  | TeamMember
  | TeamPage
  | CallToAction
  | PrivacyPage
  | AboutPage
  | ContentVideo
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
