/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TopologyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topology";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroMedia: HeroMedia;
  title: string;
  slug: Slug;
  location: string;
  topology: TopologyReference;
  status: "Completed" | "In progress" | "Concept";
  description: string;
  completionYear?: number;
  plans?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
  renders?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
  media?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
  gallery?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type HeroMedia = {
  _type: "heroMedia";
  mediaType: "image" | "video";
  image?: ContentImage;
  video?: ContentVideo;
};

export type Topology = {
  _id: string;
  _type: "topology";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  membershipStatus: "current" | "former";
  role?: string;
  portrait?: ContentImage;
  biography?: RichText;
  startYear?: number;
  endYear?: number;
  visibility: "visible" | "hidden";
  order: number;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentImage = {
  _type: "contentImage";
  asset: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  caption?: string;
};

export type TeamPage = {
  _id: string;
  _type: "teamPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  hero: HeroMedia;
  callToAction: CallToAction;
};

export type CallToAction = {
  _type: "callToAction";
  title: string;
  description: string;
  label: string;
  href: string;
  backgroundMedia: ContentMedia;
  insetMedia: ContentMedia;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: HeroMedia;
  aboutTitle: string;
  introduction: RichText;
  resources?: Array<{
    title: string;
    body: RichText;
    _key: string;
  }>;
  beliefs?: Array<{
    title: string;
    body: RichText;
    _key: string;
  }>;
  principles: Array<{
    primaryMedia: ContentMedia;
    story: {
      media: ContentMedia;
      label: string;
      statement: string;
      description: string;
      link: {
        label: string;
        href: string;
      };
    };
    _key: string;
  }>;
  callToAction: CallToAction;
};

export type ContentMedia = {
  _type: "contentMedia";
  mediaType: "image" | "video";
  image?: ContentImage;
  video?: ContentVideo;
};

export type ContentVideo = {
  _type: "contentVideo";
  url: string;
  thumbnail?: ContentImage;
  title: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TopologyReference
  | Project
  | Slug
  | HeroMedia
  | Topology
  | TeamMember
  | RichText
  | SanityImageAssetReference
  | ContentImage
  | TeamPage
  | CallToAction
  | AboutPage
  | ContentMedia
  | ContentVideo
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]  | order(_createdAt asc, title asc){      _id,  title,  "slug": slug.current,  location,  status,  description,  completionYear,  "topology": topology->{    _id,    title,    "slug": slug.current  },  heroMedia{    mediaType,    image{asset, alt},    video{      url,      title,      thumbnail{asset, alt}    }  }  }
export type WORK_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  location: string;
  status: "Completed" | "Concept" | "In progress";
  description: string;
  completionYear: number | null;
  topology: {
    _id: string;
    title: string;
    slug: string;
  };
  heroMedia: {
    mediaType: "image" | "video";
    image: {
      asset: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      alt: string | null;
    } | null;
    video: {
      url: string;
      title: string;
      thumbnail: {
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
      } | null;
    } | null;
  };
}>;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  location,  status,  description,  completionYear,  "topology": topology->{    _id,    title,    "slug": slug.current  },  heroMedia{    mediaType,    image{asset, alt},    video{      url,      title,      thumbnail{asset, alt}    }  },    plans[]{      _key,      _type,      asset,      alt,      url,      title,      thumbnail{asset, alt}    },    renders[]{      _key,      _type,      asset,      alt,      url,      title,      thumbnail{asset, alt}    },    "media": coalesce(media, gallery, [])[]{      _key,      _type,      asset,      alt,      url,      title,      thumbnail{asset, alt}    }  }
export type WORK_PROJECT_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  location: string;
  status: "Completed" | "Concept" | "In progress";
  description: string;
  completionYear: number | null;
  topology: {
    _id: string;
    title: string;
    slug: string;
  };
  heroMedia: {
    mediaType: "image" | "video";
    image: {
      asset: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      alt: string | null;
    } | null;
    video: {
      url: string;
      title: string;
      thumbnail: {
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
      } | null;
    } | null;
  };
  plans: Array<
    | {
        _key: string;
        _type: "contentImage";
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
        url: null;
        title: null;
        thumbnail: null;
      }
    | {
        _key: string;
        _type: "contentVideo";
        asset: null;
        alt: null;
        url: string;
        title: string;
        thumbnail: {
          asset: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          alt: string | null;
        } | null;
      }
  > | null;
  renders: Array<
    | {
        _key: string;
        _type: "contentImage";
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
        url: null;
        title: null;
        thumbnail: null;
      }
    | {
        _key: string;
        _type: "contentVideo";
        asset: null;
        alt: null;
        url: string;
        title: string;
        thumbnail: {
          asset: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          alt: string | null;
        } | null;
      }
  > | null;
  media:
    | Array<never>
    | Array<
        | {
            _key: string;
            _type: "contentImage";
            asset: {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
            };
            alt: string | null;
            url: null;
            title: null;
            thumbnail: null;
          }
        | {
            _key: string;
            _type: "contentVideo";
            asset: null;
            alt: null;
            url: string;
            title: string;
            thumbnail: {
              asset: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              alt: string | null;
            } | null;
          }
      >;
} | null;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECT_METADATA_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    title,    description  }
export type WORK_PROJECT_METADATA_QUERY_RESULT = {
  title: string;
  description: string;
} | null;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current  }
export type WORK_PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: HOME_FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true && defined(slug.current)]  | order(_createdAt asc, title asc){      _id,  title,  "slug": slug.current,  location,  status,  description,  completionYear,  "topology": topology->{    _id,    title,    "slug": slug.current  },  heroMedia{    mediaType,    image{asset, alt},    video{      url,      title,      thumbnail{asset, alt}    }  }  }
export type HOME_FEATURED_PROJECTS_QUERY_RESULT = Array<never>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "project" && defined(slug.current)]\n  | order(_createdAt asc, title asc){\n    \n  _id,\n  title,\n  "slug": slug.current,\n  location,\n  status,\n  description,\n  completionYear,\n  "topology": topology->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  heroMedia{\n    mediaType,\n    image{asset, alt},\n    video{\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n\n  }\n': WORK_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  location,\n  status,\n  description,\n  completionYear,\n  "topology": topology->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  heroMedia{\n    mediaType,\n    image{asset, alt},\n    video{\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n,\n    plans[]{\n      _key,\n      _type,\n      asset,\n      alt,\n      url,\n      title,\n      thumbnail{asset, alt}\n    },\n    renders[]{\n      _key,\n      _type,\n      asset,\n      alt,\n      url,\n      title,\n      thumbnail{asset, alt}\n    },\n    "media": coalesce(media, gallery, [])[]{\n      _key,\n      _type,\n      asset,\n      alt,\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n': WORK_PROJECT_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    title,\n    description\n  }\n': WORK_PROJECT_METADATA_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': WORK_PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "project" && featured == true && defined(slug.current)]\n  | order(_createdAt asc, title asc){\n    \n  _id,\n  title,\n  "slug": slug.current,\n  location,\n  status,\n  description,\n  completionYear,\n  "topology": topology->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  heroMedia{\n    mediaType,\n    image{asset, alt},\n    video{\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n\n  }\n': HOME_FEATURED_PROJECTS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
