/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TopologyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topology";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroMedia: HeroMedia;
  title: string;
  slug: Slug;
  location: string;
  topology: TopologyReference;
  status: "Completed" | "In progress" | "Concept";
  description: string;
  completionYear?: number;
  plans?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
  renders?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
  media?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
  gallery?: Array<
    | ({
        _key: string;
      } & ContentImage)
    | ({
        _key: string;
      } & ContentVideo)
  >;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type HeroMedia = {
  _type: "heroMedia";
  mediaType: "image" | "video";
  image?: ContentImage;
  video?: ContentVideo;
};

export type Topology = {
  _id: string;
  _type: "topology";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  membershipStatus: "current" | "former";
  role?: string;
  portrait?: ContentImage;
  biography?: RichText;
  startYear?: number;
  endYear?: number;
  visibility: "visible" | "hidden";
  order: number;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentImage = {
  _type: "contentImage";
  asset: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  caption?: string;
};

export type TeamPage = {
  _id: string;
  _type: "teamPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  hero: HeroMedia;
  callToAction: CallToAction;
};

export type CallToAction = {
  _type: "callToAction";
  title: string;
  description: string;
  label: string;
  href: string;
  backgroundMedia: ContentMedia;
  insetMedia: ContentMedia;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: HeroMedia;
  aboutTitle: string;
  introduction: RichText;
  resources?: Array<{
    title: string;
    body: RichText;
    _key: string;
  }>;
  beliefs?: Array<{
    title: string;
    body: RichText;
    _key: string;
  }>;
  principles: Array<{
    primaryMedia: ContentMedia;
    story: {
      media: ContentMedia;
      label: string;
      statement: string;
      description: string;
      link: {
        label: string;
        href: string;
      };
    };
    _key: string;
  }>;
  callToAction: CallToAction;
};

export type ContentMedia = {
  _type: "contentMedia";
  mediaType: "image" | "video";
  image?: ContentImage;
  video?: ContentVideo;
};

export type ContentVideo = {
  _type: "contentVideo";
  url: string;
  thumbnail?: ContentImage;
  title: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TopologyReference
  | Project
  | Slug
  | HeroMedia
  | Topology
  | TeamMember
  | RichText
  | SanityImageAssetReference
  | ContentImage
  | TeamPage
  | CallToAction
  | AboutPage
  | ContentMedia
  | ContentVideo
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries/about.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0] {    "hero": {      "mediaType": hero.mediaType,      "imageUrl": hero.image.asset.asset->url,      "imageAlt": hero.image.alt,      "videoUrl": hero.video.url,      "videoThumbnailUrl": hero.video.thumbnail.asset.asset->url,      "videoTitle": hero.video.title    },    aboutTitle,    "introduction": pt::text(introduction),     resources[] {      _key,      title,      "isExpandable": coalesce(isExpandable, true),      "body": pt::text(body)    },    beliefs[] {      title,      "body": pt::text(body)    },    principles[] {      "primaryMedia": {        "mediaType": primaryMedia.mediaType,        "imageUrl": primaryMedia.image.asset.asset->url,        "imageAlt": primaryMedia.image.alt,        "videoUrl": primaryMedia.video.url,        "videoThumbnailUrl": primaryMedia.video.thumbnail.asset.asset->url,        "videoTitle": primaryMedia.video.title      },      story {        "media": {          "mediaType": media.mediaType,          "imageUrl": media.image.asset.asset->url,          "imageAlt": media.image.alt,          "videoUrl": media.video.url,          "videoThumbnailUrl": media.video.thumbnail.asset.asset->url,          "videoTitle": media.video.title        },        label,        statement,        description,        link {          label,          href        }      }    },    callToAction {      title,      description,      label,      href,      "backgroundUrl": backgroundMedia.image.asset.asset->url,      "backgroundAlt": backgroundMedia.image.alt,      "insetUrl": insetMedia.image.asset.asset->url,      "insetAlt": insetMedia.image.alt    }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  hero: {
    mediaType: "image" | "video";
    imageUrl: string | null;
    imageAlt: string | null;
    videoUrl: string | null;
    videoThumbnailUrl: string | null;
    videoTitle: string | null;
  };
  aboutTitle: string;
  introduction: string;
  resources: Array<{
    _key: string;
    title: string;
    isExpandable: true;
    body: string;
  }> | null;
  beliefs: Array<{
    title: string;
    body: string;
  }> | null;
  principles: Array<{
    primaryMedia: {
      mediaType: "image" | "video";
      imageUrl: string | null;
      imageAlt: string | null;
      videoUrl: string | null;
      videoThumbnailUrl: string | null;
      videoTitle: string | null;
    };
    story: {
      media: {
        mediaType: "image" | "video";
        imageUrl: string | null;
        imageAlt: string | null;
        videoUrl: string | null;
        videoThumbnailUrl: string | null;
        videoTitle: string | null;
      };
      label: string;
      statement: string;
      description: string;
      link: {
        label: string;
        href: string;
      };
    };
  }>;
  callToAction: {
    title: string;
    description: string;
    label: string;
    href: string;
    backgroundUrl: string | null;
    backgroundAlt: string | null;
    insetUrl: string | null;
    insetAlt: string | null;
  };
} | null;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]  | order(_createdAt asc, title asc){      _id,  title,  "slug": slug.current,  location,  status,  description,  completionYear,  "topology": topology->{    _id,    title,    "slug": slug.current  },  heroMedia{    mediaType,    image{asset, alt},    video{      url,      title,      thumbnail{asset, alt}    }  }  }
export type WORK_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  location: string;
  status: "Completed" | "Concept" | "In progress";
  description: string;
  completionYear: number | null;
  topology: {
    _id: string;
    title: string;
    slug: string;
  };
  heroMedia: {
    mediaType: "image" | "video";
    image: {
      asset: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      alt: string | null;
    } | null;
    video: {
      url: string;
      title: string;
      thumbnail: {
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
      } | null;
    } | null;
  };
}>;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  location,  status,  description,  completionYear,  "topology": topology->{    _id,    title,    "slug": slug.current  },  heroMedia{    mediaType,    image{asset, alt},    video{      url,      title,      thumbnail{asset, alt}    }  },    plans[]{      _key,      _type,      asset,      alt,      url,      title,      thumbnail{asset, alt}    },    renders[]{      _key,      _type,      asset,      alt,      url,      title,      thumbnail{asset, alt}    },    "media": coalesce(media, gallery, [])[]{      _key,      _type,      asset,      alt,      url,      title,      thumbnail{asset, alt}    }  }
export type WORK_PROJECT_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  location: string;
  status: "Completed" | "Concept" | "In progress";
  description: string;
  completionYear: number | null;
  topology: {
    _id: string;
    title: string;
    slug: string;
  };
  heroMedia: {
    mediaType: "image" | "video";
    image: {
      asset: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      alt: string | null;
    } | null;
    video: {
      url: string;
      title: string;
      thumbnail: {
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
      } | null;
    } | null;
  };
  plans: Array<
    | {
        _key: string;
        _type: "contentImage";
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
        url: null;
        title: null;
        thumbnail: null;
      }
    | {
        _key: string;
        _type: "contentVideo";
        asset: null;
        alt: null;
        url: string;
        title: string;
        thumbnail: {
          asset: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          alt: string | null;
        } | null;
      }
  > | null;
  renders: Array<
    | {
        _key: string;
        _type: "contentImage";
        asset: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string | null;
        url: null;
        title: null;
        thumbnail: null;
      }
    | {
        _key: string;
        _type: "contentVideo";
        asset: null;
        alt: null;
        url: string;
        title: string;
        thumbnail: {
          asset: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          alt: string | null;
        } | null;
      }
  > | null;
  media:
    | Array<never>
    | Array<
        | {
            _key: string;
            _type: "contentImage";
            asset: {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
            };
            alt: string | null;
            url: null;
            title: null;
            thumbnail: null;
          }
        | {
            _key: string;
            _type: "contentVideo";
            asset: null;
            alt: null;
            url: string;
            title: string;
            thumbnail: {
              asset: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              alt: string | null;
            } | null;
          }
      >;
} | null;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECT_METADATA_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    title,    description  }
export type WORK_PROJECT_METADATA_QUERY_RESULT = {
  title: string;
  description: string;
} | null;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: WORK_PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current  }
export type WORK_PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/src/sanity/queries/projects.ts
// Variable: HOME_FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true && defined(slug.current)]  | order(_createdAt asc, title asc){      _id,  title,  "slug": slug.current,  location,  status,  description,  completionYear,  "topology": topology->{    _id,    title,    "slug": slug.current  },  heroMedia{    mediaType,    image{asset, alt},    video{      url,      title,      thumbnail{asset, alt}    }  }  }
export type HOME_FEATURED_PROJECTS_QUERY_RESULT = Array<never>;

// Source: ../web/src/sanity/queries/team.ts
// Variable: TEAM_MEMBERS_QUERY
// Query: *[_type == "teamMember" && visibility == "visible"]  | order(order asc) {    _id,    firstName,    surname,    membershipStatus,    role,    "portrait": portrait.asset.asset->url,    "biography": pt::text(biography)  }
export type TEAM_MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  firstName: null;
  surname: null;
  membershipStatus: "current" | "former";
  role: string | null;
  portrait: string | null;
  biography: string;
}>;

// Source: ../web/src/sanity/queries/team.ts
// Variable: TEAM_PAGE_QUERY
// Query: *[_type == "teamPage"][0] {    title,    "heroUrl": hero.image.asset.asset->url,    "heroAlt": hero.image.alt,    callToAction {      title,      description,      label,      href,      "backgroundUrl": backgroundMedia.image.asset.asset->url,      "backgroundAlt": backgroundMedia.image.alt,      "insetUrl": insetMedia.image.asset.asset->url,      "insetAlt": insetMedia.image.alt    }  }
export type TEAM_PAGE_QUERY_RESULT = {
  title: string;
  heroUrl: string | null;
  heroAlt: string | null;
  callToAction: {
    title: string;
    description: string;
    label: string;
    href: string;
    backgroundUrl: string | null;
    backgroundAlt: string | null;
    insetUrl: string | null;
    insetAlt: string | null;
  };
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "aboutPage"][0] {\n    "hero": {\n      "mediaType": hero.mediaType,\n      "imageUrl": hero.image.asset.asset->url,\n      "imageAlt": hero.image.alt,\n      "videoUrl": hero.video.url,\n      "videoThumbnailUrl": hero.video.thumbnail.asset.asset->url,\n      "videoTitle": hero.video.title\n    },\n    aboutTitle,\n    "introduction": pt::text(introduction), \n    resources[] {\n      _key,\n      title,\n      "isExpandable": coalesce(isExpandable, true),\n      "body": pt::text(body)\n    },\n    beliefs[] {\n      title,\n      "body": pt::text(body)\n    },\n    principles[] {\n      "primaryMedia": {\n        "mediaType": primaryMedia.mediaType,\n        "imageUrl": primaryMedia.image.asset.asset->url,\n        "imageAlt": primaryMedia.image.alt,\n        "videoUrl": primaryMedia.video.url,\n        "videoThumbnailUrl": primaryMedia.video.thumbnail.asset.asset->url,\n        "videoTitle": primaryMedia.video.title\n      },\n      story {\n        "media": {\n          "mediaType": media.mediaType,\n          "imageUrl": media.image.asset.asset->url,\n          "imageAlt": media.image.alt,\n          "videoUrl": media.video.url,\n          "videoThumbnailUrl": media.video.thumbnail.asset.asset->url,\n          "videoTitle": media.video.title\n        },\n        label,\n        statement,\n        description,\n        link {\n          label,\n          href\n        }\n      }\n    },\n    callToAction {\n      title,\n      description,\n      label,\n      href,\n      "backgroundUrl": backgroundMedia.image.asset.asset->url,\n      "backgroundAlt": backgroundMedia.image.alt,\n      "insetUrl": insetMedia.image.asset.asset->url,\n      "insetAlt": insetMedia.image.alt\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]\n  | order(_createdAt asc, title asc){\n    \n  _id,\n  title,\n  "slug": slug.current,\n  location,\n  status,\n  description,\n  completionYear,\n  "topology": topology->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  heroMedia{\n    mediaType,\n    image{asset, alt},\n    video{\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n\n  }\n': WORK_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  location,\n  status,\n  description,\n  completionYear,\n  "topology": topology->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  heroMedia{\n    mediaType,\n    image{asset, alt},\n    video{\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n,\n    plans[]{\n      _key,\n      _type,\n      asset,\n      alt,\n      url,\n      title,\n      thumbnail{asset, alt}\n    },\n    renders[]{\n      _key,\n      _type,\n      asset,\n      alt,\n      url,\n      title,\n      thumbnail{asset, alt}\n    },\n    "media": coalesce(media, gallery, [])[]{\n      _key,\n      _type,\n      asset,\n      alt,\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n': WORK_PROJECT_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    title,\n    description\n  }\n': WORK_PROJECT_METADATA_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': WORK_PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "project" && featured == true && defined(slug.current)]\n  | order(_createdAt asc, title asc){\n    \n  _id,\n  title,\n  "slug": slug.current,\n  location,\n  status,\n  description,\n  completionYear,\n  "topology": topology->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  heroMedia{\n    mediaType,\n    image{asset, alt},\n    video{\n      url,\n      title,\n      thumbnail{asset, alt}\n    }\n  }\n\n  }\n': HOME_FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "teamMember" && visibility == "visible"]\n  | order(order asc) {\n    _id,\n    firstName,\n    surname,\n    membershipStatus,\n    role,\n    "portrait": portrait.asset.asset->url,\n    "biography": pt::text(biography)\n  }\n': TEAM_MEMBERS_QUERY_RESULT;
    '\n  *[_type == "teamPage"][0] {\n    title,\n    "heroUrl": hero.image.asset.asset->url,\n    "heroAlt": hero.image.alt,\n    callToAction {\n      title,\n      description,\n      label,\n      href,\n      "backgroundUrl": backgroundMedia.image.asset.asset->url,\n      "backgroundAlt": backgroundMedia.image.alt,\n      "insetUrl": insetMedia.image.asset.asset->url,\n      "insetAlt": insetMedia.image.alt\n    }\n  }\n': TEAM_PAGE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
